### ISSUE TITLE
Make compatible with 0.4.3+ 

### ISSUE THREAD

**Issue by bsudekum** [voronianski/react-native-effects-view#2]
This component is using a couple of now depreciated APIs, see [release notes @0.4.3](https://github.com/facebook/react-native/releases/tag/v0.4.3). It'd be great to see a compatibility update.

Also, the component should not require react-native. I think it's a better practice to make react-native + a version number a `peerDependency`.

**Comment by voronianski** [comment]
@bsudekum yesss.. there are a couple of changes that should be done in order to port this to latest version. I should check docs once more 'cause last time there was no clear upgrade guide.

**Comment by voronianski** [comment]
It's solved in `0.2.0` by this PR - https://github.com/voronianski/react-native-effects-view/pull/4
